### ISSUE TITLE
Bad Request: AMOUNT_must be greater than or equal to 0.01

### ISSUE THREAD

**Issue by cooperaj** [cooperaj/starling-coinjar#10]
Appears to be submitting requests to Starling with a 0.00 amount to transfer which is not allowed.

**Comment by cooperaj** [comment]
```2018-09-28T06:42:39.460454638Z app[web.1]: 172.17.0.1 - - [28/Sep/2018:06:42:39 +0000] "POST /transaction HTTP/1.1" 200 12
2018-09-28T06:42:39.460527101Z app[web.1]: Recieved transaction of 4.800000
2018-09-28T06:42:39.694847832Z app[web.1]: panic: Cannot add funds to the "Coin Jar" coin jar: Bad Request: AMOUNT_must be greater than or equal to 0.01
2018-09-28T06:42:39.694996147Z app[web.1]:
2018-09-28T06:42:39.695252906Z app[web.1]: goroutine 29 [running]:
2018-09-28T06:42:39.695821302Z app[web.1]: github.com/cooperaj/starling-coinjar/internal/app/coinjar.(*StarlingCoinJar).AddFunds(0xc000074ff0, 0xc000310100, 0x10, 0x64)
2018-09-28T06:42:39.696117010Z app[web.1]:      /go/src/github.com/cooperaj/starling-coinjar/internal/app/coinjar/coinjar.go:52 +0x1b3
2018-09-28T06:42:39.696401669Z app[web.1]: github.com/cooperaj/starling-coinjar/internal/app/coinjar.(*StarlingTransactionProcessor).Start.func1(0xc00030dfa0)
2018-09-28T06:42:39.696757448Z app[web.1]:      /go/src/github.com/cooperaj/starling-coinjar/internal/app/coinjar/transaction.go:38 +0x109
2018-09-28T06:42:39.696876710Z app[web.1]: created by github.com/cooperaj/starling-coinjar/internal/app/coinjar.(*StarlingTransactionProcessor).Start
2018-09-28T06:42:39.697180638Z app[web.1]:      /go/src/github.com/cooperaj/starling-coinjar/internal/app/coinjar/transaction.go:32 +0xa0
```
